"""HTML report formatter"""

from typing import Dict, Any
from datetime import datetime


class HTMLFormatter:
    """Format report as HTML"""
    
    extension = "html"
    
    def format(self, data: Dict[str, Any]) -> str:
        """Convert data to HTML"""
        
        findings_html = ""
        for i, finding in enumerate(data.get('findings', []), 1):
            findings_html += f"""
            <div class="finding">
                <h3>Finding {i}</h3>
                <p><strong>Tool:</strong> <code>{finding.get('tool', 'N/A')}</code></p>
                <pre>{finding.get('summary', finding.get('output', 'N/A'))[:500]}</pre>
            </div>
            """
        
        actions_html = "\n".join([f"<li>{action}</li>" for action in data.get('actions', [])])
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>TUKUB AI Security Report</title>
    <style>
        body {{ font-family: monospace; margin: 40px; background: #0a0a0a; color: #00ff00; }}
        h1 {{ color: #ff0000; }}
        .finding {{ border: 1px solid #00ff00; margin: 20px 0; padding: 10px; }}
        pre {{ background: #1a1a1a; padding: 10px; overflow-x: auto; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #888; }}
    </style>
</head>
<body>
    <h1>TUKUB AI Security Assessment Report</h1>
    <p><strong>Generated:</strong> {datetime.now().isoformat()}</p>
    
    <h2>Summary</h2>
    <ul>
        <li><strong>Objective:</strong> {data.get('objective', 'N/A')}</li>
        <li><strong>Target:</strong> {data.get('target', 'N/A')}</li>
        <li><strong>Total Findings:</strong> {data.get('total_findings', 0)}</li>
        <li><strong>Actions Taken:</strong> {data.get('actions_taken', 0)}</li>
        <li><strong>Elapsed Time:</strong> {data.get('elapsed_time', 0)} seconds</li>
    </ul>
    
    <h2>Findings</h2>
    {findings_html}
    
    <h2>Actions Log</h2>
    <ul>{actions_html}</ul>
    
    <div class="footer">
        <hr>
        <p>Report generated by TUKUB AI - Authorized Use Only</p>
    </div>
</body>
</html>"""