"""Markdown report formatter"""

from typing import Dict, Any
from datetime import datetime


class MarkdownFormatter:
    """Format report as Markdown"""
    
    extension = "md"
    
    def format(self, data: Dict[str, Any]) -> str:
        """Convert data to markdown"""
        
        lines = [
            "# TUKUB AI Security Assessment Report",
            "",
            f"**Generated:** {datetime.now().isoformat()}",
            "",
            "## Summary",
            "",
            f"- **Objective:** {data.get('objective', 'N/A')}",
            f"- **Target:** {data.get('target', 'N/A')}",
            f"- **Total Findings:** {data.get('total_findings', 0)}",
            f"- **Actions Taken:** {data.get('actions_taken', 0)}",
            f"- **Elapsed Time:** {data.get('elapsed_time', 0)} seconds",
            "",
            "## Findings",
            ""
        ]
        
        for i, finding in enumerate(data.get('findings', []), 1):
            lines.append(f"### Finding {i}")
            lines.append("")
            lines.append(f"**Tool:** `{finding.get('tool', 'N/A')}`")
            lines.append("")
            lines.append("**Details:**")
            lines.append("```")
            lines.append(finding.get('summary', finding.get('output', 'N/A'))[:500])
            lines.append("```")
            lines.append("")
        
        lines.extend([
            "## Actions Log",
            "",
            "```"
        ])
        
        for action in data.get('actions', []):
            lines.append(f"  {action}")
        
        lines.extend([
            "```",
            "",
            "---",
            "*Report generated by TUKUB AI - Authorized Use Only*"
        ])
        
        return "\n".join(lines)