"""PDF report formatter"""

from typing import Dict, Any
from datetime import datetime
from weasyprint import HTML


class PDFFormatter:
    """Format report as PDF"""
    
    extension = "pdf"
    
    def format(self, data: Dict[str, Any]) -> str:
        """Convert data to PDF (returns HTML string for conversion)"""
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>TUKUB AI Security Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                h1 {{ color: #cc0000; }}
                .finding {{ border: 1px solid #ccc; margin: 20px 0; padding: 10px; }}
                pre {{ background: #f5f5f5; padding: 10px; overflow-x: auto; }}
                .footer {{ margin-top: 40px; font-size: 12px; color: #666; }}
            </style>
        </head>
        <body>
            <h1>TUKUB AI Security Assessment Report</h1>
            <p><strong>Generated:</strong> {datetime.now().isoformat()}</p>
            
            <h2>Summary</h2>
            <ul>
                <li><strong>Objective:</strong> {data.get('objective', 'N/A')}</li>
                <li><strong>Target:</strong> {data.get('target', 'N/A')}</li>
                <li><strong>Total Findings:</strong> {data.get('total_findings', 0)}</li>
                <li><strong>Actions Taken:</strong> {data.get('actions_taken', 0)}</li>
                <li><strong>Elapsed Time:</strong> {data.get('elapsed_time', 0)} seconds</li>
            </ul>
            
            <h2>Findings</h2>
        """
        
        for i, finding in enumerate(data.get('findings', []), 1):
            html_content += f"""
            <div class="finding">
                <h3>Finding {i}</h3>
                <p><strong>Tool:</strong> <code>{finding.get('tool', 'N/A')}</code></p>
                <pre>{finding.get('summary', finding.get('output', 'N/A'))[:500]}</pre>
            </div>
            """
        
        html_content += """
            <div class="footer">
                <hr>
                <p>Report generated by TUKUB AI - Authorized Use Only</p>
            </div>
        </body>
        </html>
        """
        
        return html_content